In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/Dataset.xlsx')
dataset.head()

S1  k1  k2  k3  k4  k5  k6  k7  klass
0   1   1   1   0   1   1   0   1      1
1   1   1   1   0   1   1   1   1      1
2   1   1   1   0   1   1   0   1      1
3   1   1   1   0   1   1   0   1      1
4   1   1   1   0   1   1   0   1      1

In [ ]:
X = dataset.drop('klass', axis=1)
Y = dataset['klass']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.80)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9988567695574065
[[ 336    3]
 [   4 5780]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       339
           1       1.00      1.00      1.00      5784

    accuracy                           1.00      6123
   macro avg       0.99      1.00      0.99      6123
weighted avg       1.00      1.00      1.00      6123



Дальше идут эксперименты

In [ ]:
dataset

S1  k1  k2  k3  k4  k5  k6  k7  klass
0      1   1   1   0   1   1   0   1      1
1      1   1   1   0   1   1   1   1      1
2      1   1   1   0   1   1   0   1      1
3      1   1   1   0   1   1   0   1      1
4      1   1   1   0   1   1   0   1      1
...   ..  ..  ..  ..  ..  ..  ..  ..    ...
7648   1   1   1   0   1   1   0   1      1
7649   1   1   1   0   1   1   0   1      1
7650   1   1   1   0   1   1   0   1      1
7651   1   1   1   0   1   1   0   1      1
7652   1   1   1   0   1   1   0   1      1

[7653 rows x 9 columns]

In [ ]:
lol = dataset.values.tolist()
scaler = StandardScaler()
scaler.fit(lol)
lol = scaler.transform(lol)
lol

array([[ 0.08109471,  0.        ,  0.03431318, ..., -0.24399191,
         0.52650065,  0.23822737],
       [ 0.08109471,  0.        ,  0.03431318, ...,  4.0984966 ,
         0.52650065,  0.23822737],
       [ 0.08109471,  0.        ,  0.03431318, ..., -0.24399191,
         0.52650065,  0.23822737],
       ...,
       [ 0.08109471,  0.        ,  0.03431318, ..., -0.24399191,
         0.52650065,  0.23822737],
       [ 0.08109471,  0.        ,  0.03431318, ..., -0.24399191,
         0.52650065,  0.23822737],
       [ 0.08109471,  0.        ,  0.03431318, ..., -0.24399191,
         0.52650065,  0.23822737]])

In [ ]:
from sklearn import preprocessing 
lol = preprocessing.normalize(dataset.values.tolist())
lol

array([[0.37796447, 0.37796447, 0.37796447, ..., 0.        , 0.37796447,
        0.37796447],
       [0.35355339, 0.35355339, 0.35355339, ..., 0.35355339, 0.35355339,
        0.35355339],
       [0.37796447, 0.37796447, 0.37796447, ..., 0.        , 0.37796447,
        0.37796447],
       ...,
       [0.37796447, 0.37796447, 0.37796447, ..., 0.        , 0.37796447,
        0.37796447],
       [0.37796447, 0.37796447, 0.37796447, ..., 0.        , 0.37796447,
        0.37796447],
       [0.37796447, 0.37796447, 0.37796447, ..., 0.        , 0.37796447,
        0.37796447]])

In [ ]:
lol = dataset.values.tolist()
i = preprocessing.normalize([lol[0]])
i

array([[0.37796447, 0.37796447, 0.37796447, 0.        , 0.37796447,
        0.37796447, 0.        , 0.37796447, 0.37796447]])