In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_excel('/content/drive/MyDrive/По гпо/Dataset_UL.xlsx')
dataset.head()

СФ1  СФ2  СФ3  СФ4  СФ5  СФ8  СФ9  П2  П7  П8  ...  ФП1.1  ФП1.2  ФП2.1  \
0    1    0    1    1    0    1    1   2   0   1  ...      1      1      1   
1    1    0    0    0    1    0    0   0   0   1  ...      1      1      1   
2    1    1    1    1    1    0    1   0   0   1  ...      1      1      1   
3    1    1    1    1    1    0    1   0   0   1  ...      1      1      1   
4    1    0    1    0    1    0    1   0   0   1  ...      1      1      1   

   ФП2.2  ФП2.3  ФП3.1  ФП4.1  ФП4.2  ФП4.3  Класс  
0      1      1      1      1      1      1      0  
1      1      1      1      1      1      1      0  
2      1      1      1      1      1      1      0  
3      1      1      1      1      1      1      0  
4      1      1      1      1      1      1      0  

[5 rows x 28 columns]

In [4]:
X = dataset.drop('Класс', axis=1)
Y = dataset['Класс']

In [6]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [37]:
clf = KNeighborsClassifier(n_neighbors=9, weights='distance', p=1)
y_pred = cross_val_predict(clf, X, Y, cv=5)
print(confusion_matrix(Y, y_pred))
print(classification_report(Y, y_pred))

[[30  0]
 [ 0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00         6

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [38]:
clf = SVC(C=8, kernel='rbf', gamma='auto', degree=1)
y_pred = cross_val_predict(clf, X, Y, cv=5)
print(confusion_matrix(Y, y_pred))
print(classification_report(Y, y_pred))

[[30  0]
 [ 0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00         6

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [33]:
clf = BernoulliNB(alpha=0.01, fit_prior=True)
y_pred = cross_val_predict(clf, X, Y, cv=5)
print(confusion_matrix(Y, y_pred))
print(classification_report(Y, y_pred))

[[30  0]
 [ 1  5]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        30
           1       1.00      0.83      0.91         6

    accuracy                           0.97        36
   macro avg       0.98      0.92      0.95        36
weighted avg       0.97      0.97      0.97        36



In [40]:
clf = DecisionTreeClassifier(max_depth=8, min_samples_split=4,
                             min_samples_leaf=1, max_features=None, splitter='random')
y_pred = cross_val_predict(clf, X, Y, cv=5)
print(confusion_matrix(Y, y_pred))
print(classification_report(Y, y_pred))

[[28  2]
 [ 0  6]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        30
           1       0.75      1.00      0.86         6

    accuracy                           0.94        36
   macro avg       0.88      0.97      0.91        36
weighted avg       0.96      0.94      0.95        36



In [42]:
clf = RandomForestClassifier(n_estimators=5, max_depth=6, min_samples_split=2, min_samples_leaf=1, max_features='sqrt', bootstrap=False)
y_pred = cross_val_predict(clf, X, Y, cv=5)
print(confusion_matrix(Y, y_pred))
print(classification_report(Y, y_pred))

[[28  2]
 [ 0  6]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        30
           1       0.75      1.00      0.86         6

    accuracy                           0.94        36
   macro avg       0.88      0.97      0.91        36
weighted avg       0.96      0.94      0.95        36



In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid = {'max_depth': range(3, 11),
              'min_samples_split': range(2, 6),
              'min_samples_leaf': range(1, 5),
              'max_features': [None, 'auto', 'sqrt', 'log2'],
              'criterion': ['gini', 'entropy'],
              'splitter': ['best', 'random']}

clf = DecisionTreeClassifier()
grid_search = GridSearchCV(clf, param_grid=param_grid, cv=5)
grid_search.fit(X, Y)
print("Наилучшие параметры: ", grid_search.best_params_)
print("Наилучшая точность: ", grid_search.best_score_)
pd.DataFrame(grid_search.cv_results_).to_excel("Tree3 - Grid.xlsx", index=False)